# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Eleanor Fleming
tagline:          'Product Portfolio'
description:      "Product professional focused on user-centered design"
url:              https://eleanorfleming96.github.io
baseurl:          ""

# Build settings
theme:            hyde
plugins:
  - jekyll-paginate
  - jekyll-gist

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/eleanorfleming96/eleanorfleming96
