# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Eleanor Fleming
tagline:          'Portfolio'
description:      "Product Portfolio"
url:              http://hyde.getpoole.com
baseurl:          /

paginate:         5

# Plugins
plugins:
  - jekyll-gist

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
